title: Ciência Aberta Ubatuba
description: "A plataforma Ciência Aberta Ubatuba estimula a articulação entre os diversos atores envolvidos com a produção e a circulação de conhecimento na cidade de Ubatuba."
baseurl: "" # If site is in a subfolder like /myrepo, set this. Otherwise, leave empty.
url: "https://cienciaabertaubatuba.github.io" # Your production URL e.g., https://cienciaabertaubatuba.github.io

collections:
  blog:
    output: true
  video:
    output: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - extract_data.py
  - jekyll_site_output/
  - README.md
